In [1]:
print("hello world")

hello world


In [2]:
1+1

2

In [3]:
print("sowmya")

sowmya


In [4]:
2**4


16

In [5]:
4%2

0

In [6]:
(2+3)*(5+5)


50

In [0]:
#this is a value
MITE=100

In [8]:
MITE

100

In [9]:
print("the value of MITE variable is",MITE)

the value of MITE variable is 100


In [10]:
'mangalore is a nice place'

'mangalore is a nice place'

In [11]:
"mangalore is great place to live"

'mangalore is great place to live'

In [15]:
number=22
name="MITE"
print(number+1,name,"is the best place to study")

23 MITE is the best place to study


In [16]:
print("my number is {one} and my name is {two}"
      .format(one=number,two=name))

my number is 22 and my name is MITE


In [17]:
x=input("enter the first number:")
y=input("enter the second number:")
i=int(x)
j=int(y)
print("the product is",i*j)

enter the first number:10
enter the second number:20
the product is 200


In [18]:
x=input("enter the first number:")
y=input("enter the second number:")
i=float(x)
j=float(y)
print("the product is",i*j)

enter the first number:1.2
enter the second number:10
the product is 12.0


In [20]:
x=input("enter the first number:")
y=input("enter the second number:")
i=bool(x)
j=bool(y)
print("the product is",i*j)


KeyboardInterrupt



In [0]:
married=bool(input("are you married ? [True|False]"))

In [13]:
"i can wrap lots of qoutes into this string"

'i can wrap lots of qoutes into this string'

In [0]:
empcode=input("enter emp code")
empname=input("enter emp name")
basesal=input("enter basic salary")
fresher=bool(input("are you fresher ? [True|False]"))
print("emp code is:",empcode)
print("emp name is:",empname)
print("basic salary is:",basesal)
print("fresher or not:",fresher)
totalsal=basesal*1.2
print(totalsal)


In [0]:
a,b=[int(x) for x in
    input("enter 2 numbers").split()]
print("product is:",a*b)

In [1]:
for i in range(1,5):
    for j in range(1,i+1):
        print('*'end)

SyntaxError: invalid syntax (<ipython-input-1-53ce3c375edf>, line 2)

In [8]:
 for i in range(0,4):
    for j in range(0,4):
        if i+j<=2:
             print(" ",end=" ")
        if i+j>=3:
             print("*",end=" ")
    print('' )

      * 
    * * 
  * * * 
* * * * 


In [9]:
name=input('enter name: ')
for i in range(len(name)):
    for j in range(0,i+1):
        print(name[i],end='')
    print()

enter name: viraat
v
ii
rrr
aaaa
aaaaa
tttttt


In [11]:
rec={}
n=int(input("enter the number ofstudents"))
i=1
while i<=n:
    name=input("enter student name:")
    marks=input("enter % marks of student")
    rec[name]=marks
    i+=1
print("name of the student","\t","% of marks")
for x in rec:
    print("\t",x,"\t\t",rec[x])

enter the number ofstudents3
enter student name:sowmya
enter % marks of student90
enter student name:sanj
enter % marks of student98
enter student name:tina
enter % marks of student67
name of the student 	 % of marks
	 sowmya 		 90
	 sanj 		 98
	 tina 		 67


In [12]:
d={100:"hello",2:'MITE',300:'sowmya'}
print(d)

{100: 'hello', 2: 'MITE', 300: 'sowmya'}


In [13]:
d[100]='sunny'

In [14]:
d


{100: 'sunny', 2: 'MITE', 300: 'sowmya'}

In [16]:
del d[300]

In [17]:
d


{100: 'sunny', 2: 'MITE'}

In [18]:
d.clear()

In [20]:
del d

NameError: name 'd' is not defined

In [21]:
d={100:"hello",2:'MITE',300:'sowmya'}
len(d)

3

In [22]:
word=input("input any word:")
d={}
for x in word:
    d[x]=d.get(x,0)+1
for k,v in d.items():
    print(k,"occur",v,"times")

input any word:hehelloooo
h occur 2 times
e occur 2 times
l occur 2 times
o occur 4 times


In [ ]:
word=input("input any word:")
d={}
vowels={'a','e','i','o','u'}
for x in word:
    for x in vowels:
        print(x)
        

In [23]:
squares={x:x*x for x in range(1,6)}
print(squares)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [24]:
n=[1,2,3,4,5,5,5,5]
print(n.count(5))

4


In [25]:
print(n.index(5))

4


In [26]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


list1=[1,2,3,'hello']
list2=[4,5,6,'índia']
list1.extend(list2)
print(list1)

###remove 

In [27]:
n.pop()

5

In [28]:
n.reverse()
print(n)

[4, 3, 2, 888, 1]


In [32]:
n=['sowmya','tina','meena','aisha']
n.sort()
print(n)

['aisha', 'meena', 'sowmya', 'tina']


In [33]:
n=['sowmya','tina','meena','aisha']
n.sort(reverse=True)
print(n)

['tina', 'sowmya', 'meena', 'aisha']


In [34]:
x=[10,20,30,40]
y=x[:]
y[1]=777
print(x)
print(y)


[10, 20, 30, 40]
[10, 777, 30, 40]


In [35]:
x=[10,20,30,40]
y=x
y[1]=777
print(x)
print(y)


[10, 777, 30, 40]
[10, 777, 30, 40]


In [36]:
x=[10,20,30,40]
y=x.copy()
y[1]=777
print(x)
print(y)


[10, 20, 30, 40]
[10, 777, 30, 40]


In [37]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)

[10, 20, 30, 40, 50, 60]


In [38]:
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [39]:
x=["MITE","mangalore","NITTE"]
y=["MITE","mangalore","NITTE"]
x==y
x!=y
z=["MITE","mangalore","NITTE"]
x==z

True

In [40]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]


60

In [41]:
m.clear()

In [42]:
n=[1,2,3,4]
print(4 in n)

True


In [43]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [44]:
words=["Mite","mysore","sowmya"]
l=[w[0] for w in words]
print(l)

['M', 'm', 's']


In [48]:
def prime() :
    flag=0
    for i in range(2,n):
        if n%i==0:
            flag=1
        if flag==1:
            return 'Not a Prime'
        else:
             return 'Prime'


In [49]:
def times2(var):
    return var*2

In [51]:
sequence=[1,2,3,4,5]
list(map(times2,sequence))

[2, 4, 6, 8, 10]

In [52]:
seq=[1,2,3,4,5]
lambda var: var*2
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [54]:
seq=[1,2,3,4,5]
lambda var: var*2
list(map(lambda var: var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [55]:
import numpy as np


In [1]:
np.eye(4)

NameError: name 'np' is not defined

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [5]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix=[[1,2,3],[4,5]]

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.random.rand(2)

array([0.13293819, 0.88480207])

In [14]:
np.random.randint(1,100,10)

array([ 1, 66, 34, 20, 44, 38, 40, 95, 24, 44])

In [9]:
np.random.rand(5,5)

array([[0.27907124, 0.14580298, 0.10631611, 0.51473788, 0.93113216],
       [0.40350101, 0.89875237, 0.05873614, 0.03462596, 0.20833566],
       [0.30059195, 0.71802143, 0.65501302, 0.46223569, 0.08638796],
       [0.85431845, 0.7193124 , 0.05910732, 0.20387088, 0.83422706],
       [0.3149969 , 0.25833504, 0.08112299, 0.21712382, 0.53157948]])

In [10]:
arr=np.arange(25)

In [11]:
runarr=np.random.randint(0,50,10)

In [12]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
runarr.max()

35

In [17]:
runarr.argmax()

7

In [19]:
runarr.argmin()

8

In [20]:
runarr.min()

6

In [29]:
arr.shape

(25,)

In [25]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [26]:
arr.reshape(1,25).shape

(1, 25)

In [27]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [28]:
arr.reshape(25,1).shape

(25, 1)

In [30]:
arr.dtype

dtype('int32')

In [32]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [34]:
arr/arr

C:\Users\Sowmyshree\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [35]:
1/arr

C:\Users\Sowmyshree\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [36]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [37]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [38]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [39]:
np.log(arr)

C:\Users\Sowmyshree\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [41]:
arr=np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[0:5]=100

In [48]:
arr=np.arange(0,11)

In [49]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [50]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.ones(15)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [60]:
arr=np.arange(5,41)
arr+arr

array([18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50,
       52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80])

In [63]:
runarr.reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)